INSERT INTO solution_types (name, description, created_at, updated_at)
VALUES
("Unknown", "Unable to determine connection between clue and solution", datetime("now"), datetime("now")),
("Anagram", "Letter rearrangement", datetime("now"), datetime("now")),
("Double straight", "Solution is possible synonym for the (often 2) clue words", datetime("now"), datetime("now")),
("Odd or even letter splice", "Either odd, even or regularly spaced letters from word sequence to form solution", datetime("now"), datetime("now")),
("Partial", "Partial anagrams requiring subclues", datetime("now"), datetime("now")),
("Double meaning", "Mis-direction clue word used in wrong context, e.g., flow-er = river", datetime("now"), datetime("now")),
("Sub-words", "Solution (literally in the clue) found from the end of one clue word and the start of the one following", datetime("now"), datetime("now")),
("Word exchange", "Solution found from solving mutliple sub clues", datetime("now"), datetime("now")),
("Lucky synonym", "Solution matches one word in the clue, but nothing else", datetime("now"), datetime("now")),
("Subtraction", "Cue word indicates letters to remove from sub-clue", datetime("now"), datetime("now")),
("Letter insertion", "Insert the answer (or sequence of letters) of a sub-clue into another.", datetime("now"), datetime("now")),
("Homophone", "Sounds like a word that has a different spelling", datetime("now"), datetime("now")),
("Initial letters", "Take the first letter from a word sequence to form the solution. Trigger words include: leaders, initially, primarily, etc.", datetime("now"), datetime("now")),
("Play on words", "Pun type clue usually with a question mark at the end as the cue", datetime("now"), datetime("now")),
("Letter shift", "Move one or more letters from the start to the end, or the other way round", datetime("now"), datetime("now")),
("Hidden in plain sight", "The solution is literally in the clue and the letters are taken from the end of one clue and the start of another.", datetime("now"), datetime("now")),
("Multiple", "Combination of different clue types", datetime("now"), datetime("now")),
("Letter reversal", "Read a word, or group of letters backwards in the clue to reveal the solution", datetime("now"), datetime("now"));