INSERT INTO crossword_setters(name, setter_type_id, description, created_at, updated_at)
VALUES
("Anarche", "4", "Unrewarding and easily distracted elsewhere. Too much word ply", datetime("now"), datetime("now")),
("Crosophile", "3", "Solvable and more enjoyable then many", datetime("now"), datetime("now")),
("Dac", "1", "The master. A rewarding blend of clues and occasionally solvable. Never wantonly obscure.", datetime("now"), datetime("now")),
("Eimi", "2", "Sometimes solvable; worth an hour or so", datetime("now"), datetime("now")),
("Glow-worm", "4", "Unrewarding and easily distracted elsewhere", datetime("now"), datetime("now")),
("Hypnos", "4", "Worth a peek if you can find a way in", datetime("now"), datetime("now")),
("Klingsor", "5", "A few clues perhaps", datetime("now"), datetime("now")),
("Monk", "4", "Not even solvable with the solutions", datetime("now"), datetime("now")),
("Mordred", "4", "Is that the washing-up that needs doing?", datetime("now"), datetime("now")),
("Morph", "4", "Unrewarding and easily distracted elsewhere", datetime("now"), datetime("now")),
("Nestor", "5", "A couple of hours of your life you're never getting back", datetime("now"), datetime("now")),
("Phi", "1", "Anagrammatic joy", datetime("now"), datetime("now")),
("Poins", "4", "And you wanted something to pass the time on a long journey", datetime("now"), datetime("now")),
("Punk", "5", "For hardcore wordplay fans. Avoid", datetime("now"), datetime("now")),
("Quixote", "2", "A relaxing way to unwind at the end of the day", datetime("now"), datetime("now")),
("Radian", "4", "Rewarding if you can crack the theme", datetime("now"), datetime("now")),
("Raich", "4", "The theme is usually out of reach", datetime("now"), datetime("now")),
("Scorpion", "5", "For hardcore wordplay fans. Avoid", datetime("now"), datetime("now")),
("Tees", "5", "An opportunity for some doodling practice. Lots of literary references.", datetime("now"), datetime("now")),
("Tyrus", "5", "Tyrus puzzles are hard to solve even when you have the answers", datetime("now"), datetime("now")),
("Hieroglyph", "1", "Sometimes gently themed puzzles", datetime("now"), datetime("now")),
("eXternal", "2", "A fair bit of wordplay", datetime("now"), datetime("now")),
("Hob", "5", "A lot of double wordplay and misdirection. For crossword buffs only.", datetime("now"), datetime("now")),
("Alchemi", "4", "A lot of wordplay", datetime("now"), datetime("now")),
("Anax", "5", "A lot of wordplay, frequently no full anagrams and often clues that don't scan. Best avoided.", datetime("now"), datetime("now")),
("Rorschach", "4", "Lots of mind games, misdirection and word play", datetime("now"), datetime("now")),
("Donk", "4", "Too much word play", datetime("now"), datetime("now")),
("Daedalus", "1", "An infrequent visitor to these shores", datetime("now"), datetime("now")),
("Knut", "4", "A right knut", datetime("now"), datetime("now")),
("Kairos", "1", "", datetime("now"), datetime("now")),
("Nimrod", "1", "An infrequent visitor to these shores", datetime("now"), datetime("now")),
("Nitsy", "1", "", datetime("now"), datetime("now"));